# fly.toml file generated for piano-notes on 2023-12-26T12:39:05-03:00

app = "piano-notes"
primary_region = "gru"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
